### ISSUE TITLE
Model document distribution category

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-model-un#4]
The distribution category may be General, Limited or Restricted  (see Editorial guidelines/Policy questions).

(http://dd.dgacm.org/editorialmanual/ed-guidelines/policy_questions/policy.htm)

**Comment by opoudjis** [comment]
The sample documents put distribution only on plenaries and not on recommendations; the editorial guidelines of the UN do not give grounds for that discrepancy, but there is going to have to be a substantial discussion with UNECE about their formatting practices anyway, if they adopt Metanorma.

Moved distribution up to general bibdata for document, since it turns out to apply to all UN documents.
