### ISSUE TITLE
Model Agenda information

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-model-un#6]
(http://dd.dgacm.org/editorialmanual/ed-guidelines/format/mast_cover.htm)

* session name
* number of agenda item
* name of agenda item
* date
* footnotes for preliminary agenda or preliminary item
* multiple agenda items (http://dd.dgacm.org/editorialmanual/ed-guidelines/format/Model_mast8.pdf)
* multiple agenda sub-items (http://dd.dgacm.org/editorialmanual/ed-guidelines/format/Model_mast21.pdf)

Agenda

In the upper left-hand corner of the cover page, under the masthead, information is given on the body concerned (in certain cases only), the session, and the number and title of the item of the agenda of that session to which the document relates.

In the case of the General Assembly, the reference is to an item of the preliminary list, or an item of the provisional agenda, or an item of the agenda as adopted at the start of the session. A footnote reference is provided for the preliminary list and the provisional agenda; there is no footnote for the adopted agenda (for more detailed information on the various stages of the agenda of the General Assembly, see Basic Documents/Documents relating to the agendas of the principal organs).

In reports and communications, a sub-item is always included after the main item, even if the two are identical, unless the sub-item is also the title of the report.

In draft resolutions, the sub-item is always included with the main item, even when they are identical and when the sub-item is also the title of the draft resolution.

In documents of the Security Council, no agenda item is given.

In the case of the Economic and Social Council, the reference is to the provisional agenda or the adopted agenda of the session. A footnote is provided for the provisional agenda only.

**Comment by opoudjis** [comment]
Already modelled: agenda item (`agenda-id`), number of agenda item (`agenda-item`), date (`session-date`), session name (`session_number`).

**Comment by opoudjis** [comment]
Implemented footnote as separate `item-footnote` document attribute. Got it to render as asterisked footnote on front page.

The problem is that Word will not permit asterisks as footnotes in first page, numbers in second section, and numbers continuing from the second section in the third section (annexes): if first section has single footnote *, and second section has single footnote 1, the third section cannot have a continuously numbered footnote 2: it will be 1 (if numbering restarts), or 3 (if numbering is continuous—because if it is continuous, it starts counting from the first section.

This counts as a bug in Word, but it's a bug that is not going to get fixed. The least offensive outcome is to restart footnote numbering for annexes at 1.

**Comment by opoudjis** [comment]
Modelled multiple agenda items and subitems. Have changed document attribute `agenda-item` to `item-number`, to differentiate it from `item-name`. Introduced `subitem-name` document attribute. This appears to be conventionally replicated as the document title by default; I am not doing so, and am allowing editors not to provide the subitem.
